# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-20 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
